# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# Site Settings
locale: "en-US"
title: "Soumen Sinha"
title_separator: "-"
subtitle: "Master’s Student at TU Delft"
name: "Soumen Sinha"
description: "Master's in Data Science & AI at TU Delft"
url: "https://soumen.github.io"
repository: "soumen/soumen.github.io"
masthead_title: "Soumen Sinha"
breadcrumbs: true
words_per_minute: 200
search: true

# Author
author:
  name: "Soumen Sinha"
  avatar: "/assets/images/avatar.jpg"
  bio: 'MS Data Science and AI at <a href="https://www.tudelft.nl" target="_blank">TU Delft</a>.'
  email: "S.Sinha-6@student.tudelft.nl"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:S.Sinha-6@student.tudelft.nl"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=zXTZqf8AAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/soumen"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/soumen_sinha/?hl=en"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/soumen-sinha-b11670211/"

# Footer
footer:
  links:
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=zXTZqf8AAAAJ&hl=en"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/soumen"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/soumen_sinha/?hl=en"

# Navigation Bar (uses _data/navigation.yml)
# File: _data/navigation.yml
navigation:
  main:
    - title: "About"
      url: /about/
    - title: "Research"
      url: /research/
    - title: "News"
      url: /#news
    - title: "CV"
      url: /assets/Soumen_CV.pdf
    - title: "Contact"
      url: mailto:S.Sinha-6@student.tudelft.nl



# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Sass
sass:
  style: compressed

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# Pagination
paginate: 5
paginate_path: /page:num/

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      custom_css: custom  # ← Enables your custom.css

# Include & Exclude
include:
  - docs/_pages
exclude:
  - CHANGELOG.md
  - vendor
  - node_modules
  - tmp
  - Gemfile
  - Gemfile.lock

# Output Settings
permalink: /:categories/:title/
encoding: "utf-8"
